networks:
  web-public:


services:
  php:
    args:
      user: kabir
      uid: 1000
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    container_name: php
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    networks:
      - web-public

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
      - database_custom_conf:/etc/mysql/conf.d
      - database_shared:/shared
    networks:
      - web-public

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    container_name: node
    volumes:
      - ./:/usr/src
      - ./node_modules:/usr/src/node_modules
    tty: true
    networks:
      - web-public

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - web-public
    ports:
      - "80:80"

volumes:
  database_data:
  database_custom_conf:
  database_shared:
