networks:
    development:


services:
    php:
        build:
            args:
                user: kabir
                uid: 1000
            context: .
            dockerfile: Dockerfile
            target: php
        container_name: php
        environment:
            - APP_ENV=${APP_ENV}
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        networks:
            - development
        ports:
            - "9000:9000"

    mysql:
        image: mysql:8.2
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - database_data:/var/lib/mysql
        networks:
            - development
        ports:
            - "3306:3306"

    # redis:
    #     image: redis:7.2-alpine
    #     container_name: redis
    #     networks:
    #         - development
    #     ports:
    #         - "6379:6379"
    node:
        build:
            context: .
            dockerfile: Dockerfile
            target: node
        container_name: node
        volumes:
            - ./:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true
        networks:
            - development

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        volumes:
            - ./:/var/www/html
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
        networks:
            - development
        ports:
            - "8080:80"

volumes:
    database_data:
